server:
  servlet:
  port: 9527
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.193.195:3306/transoirtion?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    url: jdbc:p6spy:mysql://localhost:3306/transoirtion?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: douzidong
    password: Shuojie,.123456
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#  http:
#    multipart:
#      max-file-size: 200Mb   #文件上传大小
#      max-request-size: 4000Mb  #最打请求大小
#上传位置
uploadDir: F:\mystudy\pic\
netty:
  host: 127.0.0.1
  port: 8091
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.shuojie.domain
#  configuration:
#    map-underscore-to-camel-case: true

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 3600 # 验证码超期时间
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
jedis:
  pool:
    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）


logging:
  level:
    root: warn
    com.shuojie.dao: debug
  pattern:
    console: '%p%m%n'
